#IndexError 
"""
    raised when a sequence is referenced which is out of range.
"""

array = [ 0, 1, 2 ] 
print (array[3])
