
import value_Error

print(dir(value_Error))
print(help(value_Error))


